MODEL_CONFIGS = {
    "DEMO_TINY_VIT_CONFIG": {
        "IN_IMG_SIZE": 32,
        "IN_CHANS": 3,
        "NUM_CLASSES": 10,
        "EMBED_DIMS": [4, 4, 4],
        "DEPTHS": [1, 2, 2],
        "NUM_HEADS": [2, 4, 4],
        "WINDOW_SIZES": [7, 1, 1],
        "MLP_RATIO": 4.0,
        "DROP_RATE": 0.0,
        "DROP_PATH_RATE": 0.0,
        "USE_CHECKPOINT": False,
        "MBCONV_EXPAND_RATIO": 2.0,
        "LOCAL_CONV_SIZE": 3,
    },
    "TINY_VIT_5M": {
        "IN_IMG_SIZE": 224,
        "IN_CHANS": 3,
        "NUM_CLASSES": 1000,
        "EMBED_DIMS": [64, 128, 160, 320],
        "DEPTHS": [2, 2, 6, 2],
        "NUM_HEADS": [2, 4, 5, 10],
        "WINDOW_SIZES": [7, 7, 14, 7],
        "MLP_RATIO": 4.0,
        "DROP_RATE": 0.0,
        "DROP_PATH_RATE": 0.0,
        "USE_CHECKPOINT": False,
        "MBCONV_EXPAND_RATIO": 4.0,
        "LOCAL_CONV_SIZE": 3,
    },
}
