APP = Test_CNN

# User settings
NUM_CORES?=8
#APP_CFLAGS += -DDEBUG
#APP_CFLAGS += -DOPTIMIZE     # Selects nth matmul to optimize execution
MATMUL_TYPE_FW_L0?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L0?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L0?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L1?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L1?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L1?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L2?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L2?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L2?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L3?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L3?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L3?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L4?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L4?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L4?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L5?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L5?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L5?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L6?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L6?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L6?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L7?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L7?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L7?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L8?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L8?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L8?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L9?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L9?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L9?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L10?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L10?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L10?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L11?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L11?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L11?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L12?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L12?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L12?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L13?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L13?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L13?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L14?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L14?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L14?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L15?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L15?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L15?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L16?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L16?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L16?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L17?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L17?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L17?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_FW_L18?=12         # Selects which optimized matmul to be used in FW (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_WG_L18?=12         # Selects which optimized matmul to be used in WEIGHT GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
MATMUL_TYPE_IG_L18?=12         # Selects which optimized matmul to be used in IN GRAD (see mm_manager_list.txt or "MM_manager()" body to verify which one is called)
# End of user settings

NUM_MATMULS?=24		# Available standard matmuls in the library
TRAIN_LIB=../../lib
TRAIN_LIB_SRCS=$(TRAIN_LIB)/sources
APP_SRCS = main.c net.c

APP_CFLAGS += -I. -I$(TRAIN_LIB)/include
APP_CFLAGS += -O3 -g3
APP_CFLAGS += -DFABRIC
APP_CFLAGS += -DCLUSTER
APP_CFLAGS += -DNUM_CORES=$(NUM_CORES)
APP_CFLAGS += -DPROF_NET
APP_CFLAGS += -mhwloopalign
APP_CFLAGS += -DMATMUL_TYPE_FW_L0=${MATMUL_TYPE_FW_L0}
APP_CFLAGS += -DMATMUL_TYPE_WG_L0=${MATMUL_TYPE_WG_L0}
APP_CFLAGS += -DMATMUL_TYPE_IG_L0=${MATMUL_TYPE_IG_L0}
APP_CFLAGS += -DMATMUL_TYPE_FW_L1=${MATMUL_TYPE_FW_L1}
APP_CFLAGS += -DMATMUL_TYPE_WG_L1=${MATMUL_TYPE_WG_L1}
APP_CFLAGS += -DMATMUL_TYPE_IG_L1=${MATMUL_TYPE_IG_L1}
APP_CFLAGS += -DMATMUL_TYPE_FW_L2=${MATMUL_TYPE_FW_L2}
APP_CFLAGS += -DMATMUL_TYPE_WG_L2=${MATMUL_TYPE_WG_L2}
APP_CFLAGS += -DMATMUL_TYPE_IG_L2=${MATMUL_TYPE_IG_L2}
APP_CFLAGS += -DMATMUL_TYPE_FW_L3=${MATMUL_TYPE_FW_L3}
APP_CFLAGS += -DMATMUL_TYPE_WG_L3=${MATMUL_TYPE_WG_L3}
APP_CFLAGS += -DMATMUL_TYPE_IG_L3=${MATMUL_TYPE_IG_L3}
APP_CFLAGS += -DMATMUL_TYPE_FW_L4=${MATMUL_TYPE_FW_L4}
APP_CFLAGS += -DMATMUL_TYPE_WG_L4=${MATMUL_TYPE_WG_L4}
APP_CFLAGS += -DMATMUL_TYPE_IG_L4=${MATMUL_TYPE_IG_L4}
APP_CFLAGS += -DMATMUL_TYPE_FW_L5=${MATMUL_TYPE_FW_L5}
APP_CFLAGS += -DMATMUL_TYPE_WG_L5=${MATMUL_TYPE_WG_L5}
APP_CFLAGS += -DMATMUL_TYPE_IG_L5=${MATMUL_TYPE_IG_L5}
APP_CFLAGS += -DMATMUL_TYPE_FW_L6=${MATMUL_TYPE_FW_L6}
APP_CFLAGS += -DMATMUL_TYPE_WG_L6=${MATMUL_TYPE_WG_L6}
APP_CFLAGS += -DMATMUL_TYPE_IG_L6=${MATMUL_TYPE_IG_L6}
APP_CFLAGS += -DMATMUL_TYPE_FW_L7=${MATMUL_TYPE_FW_L7}
APP_CFLAGS += -DMATMUL_TYPE_WG_L7=${MATMUL_TYPE_WG_L7}
APP_CFLAGS += -DMATMUL_TYPE_IG_L7=${MATMUL_TYPE_IG_L7}
APP_CFLAGS += -DMATMUL_TYPE_FW_L8=${MATMUL_TYPE_FW_L8}
APP_CFLAGS += -DMATMUL_TYPE_WG_L8=${MATMUL_TYPE_WG_L8}
APP_CFLAGS += -DMATMUL_TYPE_IG_L8=${MATMUL_TYPE_IG_L8}
APP_CFLAGS += -DMATMUL_TYPE_FW_L9=${MATMUL_TYPE_FW_L9}
APP_CFLAGS += -DMATMUL_TYPE_WG_L9=${MATMUL_TYPE_WG_L9}
APP_CFLAGS += -DMATMUL_TYPE_IG_L9=${MATMUL_TYPE_IG_L9}
APP_CFLAGS += -DMATMUL_TYPE_FW_L10=${MATMUL_TYPE_FW_L10}
APP_CFLAGS += -DMATMUL_TYPE_WG_L10=${MATMUL_TYPE_WG_L10}
APP_CFLAGS += -DMATMUL_TYPE_IG_L10=${MATMUL_TYPE_IG_L10}
APP_CFLAGS += -DMATMUL_TYPE_FW_L11=${MATMUL_TYPE_FW_L11}
APP_CFLAGS += -DMATMUL_TYPE_WG_L11=${MATMUL_TYPE_WG_L11}
APP_CFLAGS += -DMATMUL_TYPE_IG_L11=${MATMUL_TYPE_IG_L11}
APP_CFLAGS += -DMATMUL_TYPE_FW_L12=${MATMUL_TYPE_FW_L12}
APP_CFLAGS += -DMATMUL_TYPE_WG_L12=${MATMUL_TYPE_WG_L12}
APP_CFLAGS += -DMATMUL_TYPE_IG_L12=${MATMUL_TYPE_IG_L12}
APP_CFLAGS += -DMATMUL_TYPE_FW_L13=${MATMUL_TYPE_FW_L13}
APP_CFLAGS += -DMATMUL_TYPE_WG_L13=${MATMUL_TYPE_WG_L13}
APP_CFLAGS += -DMATMUL_TYPE_IG_L13=${MATMUL_TYPE_IG_L13}
APP_CFLAGS += -DMATMUL_TYPE_FW_L14=${MATMUL_TYPE_FW_L14}
APP_CFLAGS += -DMATMUL_TYPE_WG_L14=${MATMUL_TYPE_WG_L14}
APP_CFLAGS += -DMATMUL_TYPE_IG_L14=${MATMUL_TYPE_IG_L14}
APP_CFLAGS += -DMATMUL_TYPE_FW_L15=${MATMUL_TYPE_FW_L15}
APP_CFLAGS += -DMATMUL_TYPE_WG_L15=${MATMUL_TYPE_WG_L15}
APP_CFLAGS += -DMATMUL_TYPE_IG_L15=${MATMUL_TYPE_IG_L15}
APP_CFLAGS += -DMATMUL_TYPE_FW_L16=${MATMUL_TYPE_FW_L16}
APP_CFLAGS += -DMATMUL_TYPE_WG_L16=${MATMUL_TYPE_WG_L16}
APP_CFLAGS += -DMATMUL_TYPE_IG_L16=${MATMUL_TYPE_IG_L16}
APP_CFLAGS += -DMATMUL_TYPE_FW_L17=${MATMUL_TYPE_FW_L17}
APP_CFLAGS += -DMATMUL_TYPE_WG_L17=${MATMUL_TYPE_WG_L17}
APP_CFLAGS += -DMATMUL_TYPE_IG_L17=${MATMUL_TYPE_IG_L17}
APP_CFLAGS += -DMATMUL_TYPE_FW_L18=${MATMUL_TYPE_FW_L18}
APP_CFLAGS += -DMATMUL_TYPE_WG_L18=${MATMUL_TYPE_WG_L18}
APP_CFLAGS += -DMATMUL_TYPE_IG_L18=${MATMUL_TYPE_IG_L18}
APP_LDFLAGS += -lm

# STATISTICS
APP_CFLAGS += -DSTATS

# SOURCES
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_act_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_conv_dw_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_conv_pw_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_conv2d_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_im2col_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_linear_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_losses_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_matmul_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_optimizers_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_pooling_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_residual_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_instnorm_fp32.c
APP_SRCS += $(TRAIN_LIB_SRCS)/pulp_train_utils_fp32.c

# RULES
get_golden:
	python ./utils/GM.py

include $(RULES_DIR)/pmsis_rules.mk
